### ISSUE TITLE
Packet send verbose in console.

### ISSUE THREAD

**Issue by mibby** [aegistudio/MapPainting#3]
https://github.com/aegistudio/MapPainting/blob/e61b2beaf5372f0c9043aa5d030148680195efdd/main/java/net/aegistudio/mpp/canvas/CanvasSwitchListener.java#L35

Packet send 1/2 is outputting to my console when players use a canvas (snake script game).

**Comment by aegistudio** [comment]
Just removed it.

I don't even noticed when did I add such debugging output, but it is removed now.

**Comment by mibby** [comment]
Thanks. :)
